Hor domain
MeteoSwiss-APN/dawn pull request #1027
Opened 2020-10-01 09:55 UTC by mroethlin

## Technical Description

Describe here what the PR does

### Resolves / Enhances

Put the link to the issue here
(e.g resolves #XXX)

### Example

If a specific example is being fixed, put it here

### Testing

If anything besides a simple launch needed (perf-test), link it here

### Dependencies

If this is built on top of anything else, put it here

2020-10-05 11:44 UTC, mroethlin commented
launch jenkins

2020-10-05 11:45 UTC, mroethlin commented
launch jenkins

2020-10-05 13:09 UTC, Stagno requested changes
Enumerating in the generated code all the possible markers (`UnstructuredIterationSpace`) conflicts with the frontend design choice to be able to define your own markers. I see two philosophies here, we should maybe have a discussion with the team:
- "LateralBoundary, Nudging, Interior, Halo, End" are all the possible markers that you'll ever need when coding an unstructured model and they are not only specific to ICON (btw `Halo` should be removed once we move entirely halo exchanges from the fortran driver into the DSL world). Dusk should expose to the user only the above markers and map them internally to Dawn's magic numbers. In this case, the user shouldn't be able to set his/her own markers (no definitions.py), as they are already defined as DSL keywords.
- There could be more (less) than just those 5. The DSL user decides.
	  Implementation is more complex. Frontend lets the user define markers, which are string tags to be passed to dawn4py. In order to retain the dawn implementation through `Interval` (which mandates magic integers), a map from string tag to magic integer should be added to the metadata, so that, on both the frontend and backend interfaces, Dawn exposes meaningful string tags instead of integers.

Example dawn4py API:
```
# order imposes magic-numbering (LateralBoundary=1, Nudging1=2, ...)
markers = dawn4py.make_markers("LateralBoundary", "Nudging1", "Nudging2", "Interior", "End") 
myInterval = dawn4py.make_interval(markers, "LateralBoundary", "Nudging2")
```
Example gen. code API:
```
void set_marker_index(LocationType loc, std::string marker, int offset, int index);
```

2020-10-06 06:59 UTC, mroethlin commented
launch jenkins

2020-10-06 08:13 UTC, mroethlin commented
launch jenkins

2020-10-06 09:04 UTC, Stagno approved these changes

2020-10-06 09:18 UTC, merged