Properly Version Sparse Fields
MeteoSwiss-APN/dawn pull request #1035
Opened 2020-10-07 12:35 UTC by mroethlin

## Technical Description

This dusk code
```
@stencil
def various_expression(
    edge_3d_field1: Field[Edge, K],
    sparse_3d_field1: Field[Edge > Cell > Vertex > Edge, K],
):
    with levels_upward:
        edge_3d_field1 = min_over(Edge > Cell > Vertex > Edge, sparse_3d_field1)
        with sparse[Edge > Cell > Vertex > Edge]:
            sparse_3d_field1 = edge_3d_field1[Edge]
```
leads to two stages
```
sparse_3d_field1_0[<no_horizontal_offset>,0] = sparse_3d_field1[<no_horizontal_offset>,0]
```
and
```
edge_3d_field1[<no_horizontal_offset>,0] = Reduce (min, init = double_type 1.79769313486231571e+308, location = {Edge, Cell, Vertex, Edge}): sparse_3d_field1_0[<has_horizontal_offset>,0];",
for ({Edges, Cell, Vertices, Edges) {
	sparse_3d_field1[<has_horizontal_offset>,0] = edge_3d_field1[<no_horizontal_offset>,0];
}
```

Which trips up the `UnstructuredDimensionsChecker` in the first stage (since assigning to sparse fields is only allowed in `ForLoopStmt`s. This PR makes sure that dawn inserts a proper `ForLoopStmt` in this case. 

### Resolves / Enhances

Fixes #1032

### Testing

A new test added to `TestPassFieldVersioning` in the style of `TestPassRemoveScalars`.

### Dependencies

This PR is independent.

2020-10-07 12:35 UTC, mroethlin commented
launch jenkins

2020-10-07 13:46 UTC, mroethlin commented
launch jenkins

2020-10-09 16:03 UTC, Stagno reviewed
The field versioning and stage split shouldn't have been triggered in the first place, because there's no race condition.
Consider this simplified (omitting k, using Edge > Cell > Edge instead of the longer one) code generation of the stencil:
```
// |Edge > Cell > Edge| = 4
for (int edgeIdx : edges()) {
	edge_3d_field1(edgeIdx) = +inf;
	for(int neigh = 0; neigh < 4; ++neigh) {
		edge_3d_field1(edgeIdx) = std::min(edge_3d_field1(edgeIdx), sparse_3d_field1(edgeIdx, neigh));
	}

	for(int neigh = 0; neigh < 4; ++ neigh) {
		sparse_3d_field1(edgeIdx, neigh) = edge_3d_field1(edgeIdx);
	}
}
```

2020-10-13 07:01 UTC, mroethlin commented
> The field versioning and stage split shouldn't have been triggered in the first place, because there's no race condition.
> Consider this simplified (omitting k, using Edge > Cell > Edge instead of the longer one) code generation of the stencil:
> 
> ```
> // |Edge > Cell > Edge| = 4
> for (int edgeIdx : edges()) {
> 	edge_3d_field1(edgeIdx) = +inf;
> 	for(int neigh = 0; neigh < 4; ++neigh) {
> 		edge_3d_field1(edgeIdx) = std::min(edge_3d_field1(edgeIdx), sparse_3d_field1(edgeIdx, neigh));
> 	}
> 
> 	for(int neigh = 0; neigh < 4; ++ neigh) {
> 		sparse_3d_field1(edgeIdx, neigh) = edge_3d_field1(edgeIdx);
> 	}
> }
> ```

you are right about that, it should only have been triggered if the second statement would read
```
        with sparse[Edge > Cell > Vertex > Edge]:
            sparse_3d_field1 = edge_3d_field1[Edge > Cell > Vertex > Edge]
```

unfortunately, as discussed yesterday, simply adding an "is offset true" check to the dependency analysis is not enough since it would lead to additional false positives:

* non-offset (in the gen. code dense access index is pidx)
```
dense_field_edges = reduce(
    Edges > Cells,
    sparse_field_e_c
  )
```
* offset (in the gen. code dense access index is nbhIdx)
```
dense_field_edges = reduce(
  Edges > Verts > Edges,
  reduce(
    Edges > Cells,
    sparse_field_e_c
  )
)
```
so potential race conditions can only occur in the second, but not in the first. This would entail that we also properly set and respect the horizontal offset flag in reductions (which would also need to happen starting from dusk). 

I'd argue that this PR is still worthwhile. Not every fill stage of a sparse field is a "false positive", so this needs to work. This PR does exactly that.

2020-10-13 09:50 UTC, Stagno requested changes
I'm also now convinced that the fix implemented here is still useful, however i suggest changing the test so that it won't become obsolete soon(-ish).

2020-10-13 09:50 UTC, Stagno commented on dawn/test/unit-test/dawn/Optimizer/TestPassFieldVersioning.cpp
> +                  {LocType::Edges, LocType::Cells, LocType::Vertices, LocType::Edges}))))));
This test is currently testing a transformation that shouldn't happen. When field versioning of sparse fields will be fixed this should maybe become a negative test. I suggest commenting it out and have the following positive test instead:
```
dense_field_edges = reduce(
  Edges > Verts > Edges,
  reduce(
    Edges > Cells,
    sparse_field_e_c
  )
)
with sparse[Edges > Cells]:
  sparse_field_e_c = dense_field_edges[Edges]
```
(much can be reused from the code below i think)

2020-10-13 12:02 UTC, mroethlin commented
launch jenkins

2020-10-13 12:05 UTC, mroethlin commented
launch jenkins

2020-10-13 12:25 UTC, Stagno approved these changes

2020-10-13 12:31 UTC, merged