Ensure Correct Dimensions in Field Assignments
MeteoSwiss-APN/dawn pull request #1036
Opened 2020-10-08 07:29 UTC by mroethlin

## Technical Description

Describe here what the PR does

### Resolves / Enhances

Put the link to the issue here
(e.g resolves #XXX)

### Example

If a specific example is being fixed, put it here

### Testing

If anything besides a simple launch needed (perf-test), link it here

### Dependencies

If this is built on top of anything else, put it here

2020-10-08 07:29 UTC, mroethlin commented
launch jenkins

2020-10-08 07:30 UTC, mroethlin commented
launch jenkins

2020-10-13 07:58 UTC, mroethlin commented
launch jenkins

2020-10-13 10:27 UTC, Stagno requested changes
Implementation is ok. One test to change and other minor suggestions.

2020-10-13 10:27 UTC, Stagno commented on dawn/src/dawn/SIR/SIR.h
> +  int numDimensions() const;
I'd suggest also here a change of name to avoid potential misunderstandings: `numSpatialDimensions()`, do you agree?

2020-10-13 10:27 UTC, Stagno commented on dawn/src/dawn/Validator/IntegrityChecker.cpp
> +                        std::to_string(rightDim) + "d field!");
```suggestion
    auto dimToStr = [](int d) {
        switch(d) {
        case 1:
            return "vertical";
        case 2:
            return "horizontal";
        case 3:
            return "full";
        default:
            return "";
        }
    };
    throw SemanticError("trying to assign " + dimToStr(leftDim) + " field to " +
                        dimToStr(rightDim) + " field!");
```
Also here same ambiguity concern when reporting errors, as in the other PR.

2020-10-13 10:27 UTC, Stagno commented on dawn/test/unit-test/dawn/Validator/TestIntegrityChecker.cpp
> +}
It says 2d3d but it's the same test as the one below (1d3d)

2020-10-13 11:01 UTC, mroethlin commented
launch jenkins

2020-10-13 11:02 UTC, mroethlin commented
launch jenkins

2020-10-13 11:03 UTC, mroethlin commented
launch jenkins

2020-10-13 11:13 UTC, mroethlin commented
launch jenkins

2020-10-13 12:27 UTC, Stagno approved these changes

2020-10-13 12:32 UTC, merged