Ensure Location Type Consistency in IfStmt
MeteoSwiss-APN/dawn pull request #1076
Opened 2020-12-01 16:47 UTC by mroethlin

## Technical Description

So far we failed to ensure location type consistency in between the conditional, then and else branch of of an `IfStmt`. This allowed code like:
```
@stencil
def if_condition(hC_x: Field[Cell],
                boundary_edges: Field[Edge]):
    with levels_downward:
        if boundary_edges:
            hC_x = 0
```
To go through the pipeline, being generated into potentially unsafe code. 

### Resolves / Enhances

Fixes #1064 

### Example

See above

### Testing

Death test added. **TODO** add more tests, consider also nested if then else

### Dependencies

This PR is independent.

2020-12-02 10:43 UTC, mroethlin commented
launch jenkins

2020-12-02 10:44 UTC, mroethlin commented
launch jenkins

2020-12-02 12:55 UTC, mroethlin commented
launch jenkins

2020-12-02 15:07 UTC, Stagno requested changes
Suggesting a different way to implement the check that covers more cases, see comment.

2020-12-04 14:46 UTC, Stagno commented
launch jenkins

2020-12-04 15:08 UTC, Stagno approved these changes

2020-12-04 15:08 UTC, merged