Extend Redcution Expression and Fill Statement to Allow Inclution of Center
MeteoSwiss-APN/dawn pull request #1081
Opened 2020-12-08 16:42 UTC by mroethlin

## Technical Description

**TODO**

2020-12-09 10:15 UTC, mroethlin commented
launch jenkins

2020-12-09 10:20 UTC, mroethlin commented
launch jenkins

2020-12-10 17:09 UTC, Stagno reviewed
You are adding `includeCenter` in 3 classes:
- reduction
- sparse loop
- sparse field descriptor

and the corresponding protobuf, IIRBuilder methods, dawn4py bindings.
It feels like there's repetition that can be avoided.

I propose an alternative:
Replace all neighbor chains (`std::vector<LocationType>`) with an `UnstructuredIterationSpace`
```
struct UnstructuredIterationSpace {
	std::vector<LocationType> NeighborChain;
	bool IncludeCenter = false;

	UnstructuredIterationSpace(std::vector<LocationType> chain) : NeighborChain(chain) {}
	UnstructuredIterationSpace(std::vector<LocationType> chain, bool includeCenter) : NeighborChain(chain), IncludeCenter(includeCenter) { 
		if(includeCenter && chain.front() != chain.back()) 
			throw std::syntax_error("..."); 
	}
	operator std::vector<LocationType>() const { return NeighborChain; }
}
```

- encapsulates the concept of iteration space (neighborhood + whether to include center or not), instead of scattering it across its container (reduction, sparse loop, or sparse field descriptor) 
- also encapsulates `includeCenter && chain.front() != chain.back()` check instead of repeating it
- can directly compare `iterSpace1 == iterSpace2` (e.g. merging of sparse iterations in the future)
- cast-able (implicitly) into `std::vector<LocationType>` for those analyses that don't care if the center is included or not, and viceversa can cast implicitly a `std::vector<LocationType>` into `UnstructuredIterationSpace` (will be constructed with `IncludeCenter` false as default).
- dont' need to explictly set the "including center" context when visiting reduction/sparse loop, e.g. cuda-ico codegen's `parentIterationIncludesCenter*_`, the info would be retrievable from the current iteration space (substituting the current neighbor chain)

2020-12-15 07:05 UTC, mroethlin commented
launch jenkins

2020-12-15 07:07 UTC, mroethlin commented
launch jenkins

2020-12-15 07:50 UTC, mroethlin commented
launch jenkins

2020-12-15 08:01 UTC, mroethlin commented
launch jenkins

2020-12-17 11:21 UTC, Stagno requested changes
Few last remarks. But overall it's good.

- The serialized representation, in which you have the unstructured iteration space encapsulated in one message, is translated into constructor calls that take `chain, includeCenter` pairs. Is there a reason to separate the two again in such calls? (the alternative would be converting directly `protoIterSpace` into an `UnstructuredIterationSpace`) Has dawn4py anything to do with that?

- Also I noticed that toylib was not updated wrt this change.

2020-12-17 12:13 UTC, mroethlin commented on dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
> +                          (hdims.getIncludeCenter() ? "+1" : "") + ", " + kSizeStr + ")");
good catch!

2020-12-17 16:16 UTC, Stagno approved these changes
One optional improvement to consider, but it's good to go already.

2020-12-18 07:50 UTC, mroethlin commented
launch jenkins

2020-12-18 07:50 UTC, mroethlin commented
launch jenkins

2020-12-18 09:47 UTC, mroethlin commented
launch jenkins

2020-12-18 10:06 UTC, merged