Subdomain Fixes
MeteoSwiss-APN/dawn pull request #1109
Opened 2021-02-09 14:42 UTC by mroethlin

## Technical Description

A few bug fixes related to subdomains:
* correct an off by one in horizontal size
* fixes number of threads vs stride confusion

Furthermore:
Small improvement in the serialization code

### Testing

Can only be tested in integration

### Dependencies

This PR is independent

2021-02-11 11:00 UTC, mroethlin commented
launch jenkins

2021-02-11 14:56 UTC, mroethlin commented
launch jenkins

2021-02-12 09:21 UTC, Stagno requested changes
Minor adjustment, then gtg.

2021-02-12 09:21 UTC, Stagno commented on dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
>                                          : "mesh_.NumVertices");
Noticed that we have a lot of code repetition here: can factorize out common part and leave switch to map location type enum to `Cells`/`Edges`/`Vertices` string (we should have this function somewhere, maybe to the singular version of the string?).
```
          return (iterSpace.has_value() ? "mesh_.Domain({::dawn::LocationType::" + toStringPlural(loc) + "," +
                                              spaceMagicNumToEnum(iterSpace->upperBound()) + "," +
                                              spaceMagicNumToEnum(iterSpace->upperLevel()) + "," +
                                              std::to_string(iterSpace->upperOffset()) + "})" +
                                              "- mesh_.Domain({::dawn::LocationType::" + toStringPlural(loc) + "," +
                                              spaceMagicNumToEnum(iterSpace->lowerBound()) + "," +
                                              std::to_string(iterSpace->lowerOffset()) + "})"
                                              spaceMagicNumToEnum(iterSpace->lowerLevel()) + "," +
                                              std::to_string(iterSpace->lowerOffset()) + "}) + 1"
                                        : "mesh_.Num" + toStringPlural(loc) + ");
```

2021-02-12 09:21 UTC, Stagno commented on dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
>            throw std::runtime_error("Invalid location type");
Also here (see comment on code above)

2021-02-12 16:11 UTC, mroethlin commented
launch jenkins

2021-02-12 16:14 UTC, mroethlin commented
launch jenkins

2021-02-12 16:27 UTC, Stagno requested changes
Spotted a typo

2021-02-12 16:27 UTC, Stagno commented on dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
> +      runFun.addStatement("int " + hSizeString + " = " g
```suggestion
      runFun.addStatement("int " + hSizeString + " = " +
```

2021-02-12 16:45 UTC, Stagno approved these changes
Approved after typo fix

2021-02-15 07:17 UTC, mroethlin commented
launch jenkins

2021-02-15 07:43 UTC, merged