Fix Serialization
MeteoSwiss-APN/dawn pull request #1125
Opened 2021-03-19 13:25 UTC by mroethlin

## Technical Description

The serialization routines had some problems:

* Calling the destructor the second time a serialization routine is called is not safe. A single stencil may serialize multiple fields in the same iteration
* The use of `rdbuf` caused some problems. See also this [stackoverflow question](https://stackoverflow.com/questions/324711/writing-stringstream-contents-into-ofstream) (later answers)

### Testing

Tested using ICON-DSL

### Dependencies

No dependencies

2021-03-31 09:17 UTC, Stagno requested changes
Small changes requested, see comments.

2021-03-31 09:17 UTC, Stagno commented on dawn/src/driver-includes/to_vtk.cpp
> -  }
> Calling the destructor the second time a serialization routine is called is not safe. A single stencil may serialize multiple fields in the same iteration

Hmm, I don't see how it's possible that the destructor of the same object gets called more than once, as once the entry of `stencil_to_output_map` with some key is deleted (which entails 1 call to the destructor), the next time the condition (of the if) is going to be evaluated to false, as the key is not going to be present anymore.
Moreover this code destroys the object for the same stencil but for the previous iteration (`iter - 1`), for which all fields have already been serialized.
I think the problem then it's somewhere else, but ....

2021-03-31 09:17 UTC, Stagno commented on dawn/src/driver-includes/to_vtk.cpp
> +}
```suggestion
void serialize_flush_iter(const char stencil_name[50], int iter) {
  flushAtIter(std::string(stencil_name), iter);
}
```

2021-03-31 09:17 UTC, Stagno commented on dawn/src/driver-includes/to_vtk.h
> +void serialize_flush_iter(const char field_name[50], int iter);
```suggestion
void serialize_flush_iter(const char stencil_name[50], int iter);
```

2021-03-31 09:17 UTC, Stagno commented on dawn/src/driver-includes/to_vtk.cpp
> +  stencil_to_output_map.erase(std::make_pair(stencil_name, iter - 1));
... this solution is cleaner, however it adds implicitly an assumption that was not there before: that the same stencil (same stencil name string) won't be called more than once in the same time iteration. Therefore I suggest to add this assumption somewhere here: https://docs.google.com/document/d/1ac0Z_8K_2mxU_fsR-9I_ih0KWry34bPOeydD8KyDiHM/edit#heading=h.1uyg0j7e7p8t
```suggestion
  stencil_to_output_map.erase(std::make_pair(stencil_name, iter));
```
Also, why flushing the previous iteration here? I think you want to flush the current one in `flushAtIter()`

2021-04-08 09:22 UTC, mroethlin commented
launch jenkins

2021-04-08 09:22 UTC, mroethlin commented
launch jenkins

2021-04-08 13:19 UTC, Stagno approved these changes

2021-04-08 13:26 UTC, merged