Remove conditional for missing value on pentagons
MeteoSwiss-APN/dawn pull request #1128
Opened 2021-04-15 08:35 UTC by cosunae

## Technical Description

WIP

### Resolves / Enhances

Put the link to the issue here
(e.g resolves #XXX)

### Example

If a specific example is being fixed, put it here

### Testing

If anything besides a simple launch needed (perf-test), link it here

### Dependencies

If this is built on top of anything else, put it here

2021-04-16 12:46 UTC, cosunae reviewed
revert block size changes (different PR)

2021-04-16 12:46 UTC, cosunae commented on dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
> +  gridFun.addStatement("return dim3((elSize + BLOCK_SIZE - 1) / BLOCK_SIZE, dK, 1)");
```suggestion
  gridFun.addStatement(
      "return dim3((elSize + BLOCK_SIZE - 1) / BLOCK_SIZE, (dK + BLOCK_SIZE - 1) / BLOCK_SIZE, 1)");
```

2021-04-16 12:46 UTC, cosunae commented on dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
> +  runFun.addStatement("dim3 dB(BLOCK_SIZE, 1, 1)");
```suggestion
  runFun.addStatement("dim3 dB(BLOCK_SIZE, BLOCK_SIZE, 1)");
```

2021-04-16 12:46 UTC, cosunae commented on dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
> +                         "- mesh_.DomainLower({::dawn::LocationType::" + locToStringPlural(loc) +
```suggestion
                                                  "- mesh_.DomainLower({::dawn::LocationType::" + locToStringPlural(loc) + "," +
```

2021-04-16 12:46 UTC, cosunae commented on dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
> +                         "," + spaceMagicNumToEnum(iterSpace->lowerLevel()) + "," +
```suggestion
                         spaceMagicNumToEnum(iterSpace->lowerLevel()) + "," +
```

2021-04-16 12:46 UTC, cosunae commented on dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
> +      "#define BLOCK_SIZE 128",
```suggestion
      "#define BLOCK_SIZE 16",
```

2021-04-16 12:46 UTC, cosunae commented on dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
> +      "#define LEVELS_PER_THREAD 4",
```suggestion
      "#define LEVELS_PER_THREAD 1",
```

2021-04-16 12:47 UTC, cosunae commented on dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
> +                                                  "- mesh_.DomainLower({::dawn::LocationType::" + locToStringPlural(loc) + "," +
```suggestion
                         "- mesh_.DomainLower({::dawn::LocationType::" + locToStringPlural(loc) + "," +
```

2021-04-16 12:48 UTC, cosunae commented
launch jenkins

2021-04-19 07:49 UTC, Stagno requested changes
small change, then good to go

2021-04-19 07:49 UTC, Stagno commented on dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp
> +  assert(chain.size() > 1);
```suggestion
  DAWN_ASSERT(chain.size() > 1);
```

2021-04-20 10:21 UTC, cosunae commented
I commited your suggestion @Stagno . can you approve it then ?

2021-04-21 12:17 UTC, Stagno approved these changes

2021-04-21 12:25 UTC, merged