Use numpy isclose-like verification, allow per field tolerances
MeteoSwiss-APN/dawn pull request #1136
Opened 2021-05-14 11:21 UTC by muellch

## Technical Description

Now use `numpy.isclose`-inspired verification method using the following formula:
```
abs(dsl[pidx] - fortran[pidx]) <= (abs_tol + rel_tol * abs(fortran[pidx]))
```
The user now can also provide `abs_tol` and `rel_tol` per OUT/INOUT field and not per kernel. There are default values in place for `abs_tol=0.0` and `rel_tol=1e-12`.

### Resolves

The relative error formula below could lead to false positives in verification failure:
```
 double error = 0.;
    if(expected == actual) {
    } else if(fabs(expected) < 1e-6 && fabs(actual) < 1e-6) {
      error = fabs(expected - actual);
    } else {
      error = fabs((expected - actual) / expected);
    }
```
This is no longer in dawn.

2021-05-14 12:18 UTC, muellch commented
launch jenkins

2021-05-17 09:47 UTC, Stagno requested changes
A small improvement requested, otherwise good to go.

2021-05-17 09:47 UTC, Stagno commented on dawn/src/driver-includes/cuda_verify.cpp
> +  gpuErrchk(cudaPeekAtLastError());
I like the overview of the dataset printed by the code below.
I'd also give an overview of the errors here, i.e. print always both the max (currently printed) and min relative and absolute errors. Not sure about the avg.
Providing more infos here helps in reducing the number of times we need to download the vtk/csv files and visualize them.

2021-05-17 10:53 UTC, Stagno commented
@muellch also need to fix icondusk-e2e which becomes incompatible with the API changes i think: http://jenkins-mch.cscs.ch/job/icondusk-e2e_PR/118/slave=tsa/console

2021-05-18 08:26 UTC, muellch commented
launch jenkins

2021-05-18 09:06 UTC, Stagno requested changes

2021-05-18 09:06 UTC, Stagno commented on dawn/src/driver-includes/cuda_verify.cpp
> +  std::cout << "[DSL] " << name << " absolute error: " << std::scientific << maxAbsErr << "\n"
missing "maximum"

2021-05-18 09:06 UTC, Stagno commented on dawn/src/driver-includes/cuda_verify.cpp
> +  std::cout << "[DSL] " << name << " absolute error: " << std::scientific << minAbsErr << "\n"
missing "minimum"

2021-05-18 09:15 UTC, muellch commented
launch jenkins

2021-05-18 09:58 UTC, merged