Make Block Size and Levels per Thread an Option to Codegen
MeteoSwiss-APN/dawn pull request #1139
Opened 2021-05-27 11:24 UTC by mroethlin

## Technical Description

Levels per thread and block size were hardcoded based an preliminary tests on daint. Tests on tsa have shown that these values need to be tuneable per stencil (i.e. there is no "global" optimum). This PR introduces the possibility to specify these parameters using command line args to `dawn-codegen`

### Example
```
./dawn-codegen --levels-per-thread=42 --block-size=1337 test_reduce.iir -b cuda-ico -o out.cpp && code out.cpp
```

### Testing

Tested manually

### Dependencies

This PR is independent.

2021-06-04 08:54 UTC, Stagno requested changes
Small change then good to go

2021-06-07 07:48 UTC, Stagno approved these changes
gtg!

2021-06-07 07:54 UTC, mroethlin commented
launch jenkins

2021-06-07 07:54 UTC, mroethlin commented
launch jenkins

2021-06-07 09:07 UTC, merged